---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Before submitting an issue, please check the FAQ: https://www.aiflygo.com/docs/msfs-map-enhancement/faq/

  - type: input
    id: bug_description
    attributes:
      label: Describe the bug
      description: Please describe the bug in detail to help understand the scenario
      placeholder: A clear and concise description of what the bug is
    validations:
      required: true

  - type: dropdown
    id: msfs_version
    attributes:
      label: MSFS version
      description: Select your MSFS version
      options:
        - MS Store / MSFS 2020
        - MS Store / MSFS 2024
        - Steam / MSFS 2020
        - Steam / MSFS 2024
    validations:
      required: true

  - type: input
    id: mod_version
    attributes:
      label: Mod version
      description: Enter the mod version you are using
      placeholder: e.g., v7.3.0
    validations:
      required: true

  - type: input
    id: device_id
    attributes:
      label: Device ID
      description: Please provide your Device ID, the Device ID can be found in the license page.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If possible, provide screenshots of the mod and MSFS
      placeholder: You can paste images here or drag-and-drop them into this box

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here
