export const EVENT_START_SERVER = "EVENT_START_SERVER";
export const EVENT_START_GAME= "EVENT_START_GAME";
export const EVENT_STOP_SERVER = "EVENT_STOP_SERVER";
export const EVENT_CHECK_PORT = "EVENT_CHECK_PORT";
export const EVENT_CHECK_UPDATE = "EVENT_CHECK_UPDATE";
export const EVENT_COLLECT_LOGS = "EVENT_COLLECT_LOGS";
export const EVENT_CHECK_LICENCE = "EVENT_CHECK_LICENCE";