export const EVENT_START_SERVER = "EVENT_START_SERVER";
export const EVENT_STOP_SERVER = "EVENT_STOP_SERVER";
export const EVENT_CHECK_PORT = "EVENT_CHECK_PORT";
export const EVENT_CHECK_UPDATE = "EVENT_CHECK_UPDATE";
